### ISSUE TITLE
Missing amino acid position

### ISSUE THREAD

**Issue by Bianca-T** [robinandeer/puzzle#124]
Hi,

In the individual page for each variant it would be great to have HGVS nomenclature implemented for coding and splice site mutations (as in Scout).

A possibly faster alternative to implement is to have the number of the amino acid position in the transcript table.

Thanks,
Bianca

**Comment by moonso** [comment]
Ok, will look into this

**Comment by moonso** [comment]
It has to do with what gemini extracts from vep/snpeff. We will try to get a more informative value to show.

**Comment by moonso** [comment]
@Bianca-T @vasiliosz I can not find a relevant annoation from gemini to enter here...
Please come with suggestions!

**Comment by vasiliosz** [comment]
aa_change and aa_length?

Skickat från min iPhone

**Comment by moonso** [comment]
Ok so should it look like `G/E, 80/362` ?

**Comment by Bianca-T** [comment]
Yes, alternatively you can merge the information from the two columns into `G80E`, but this will be complicated for splice variants and frameshift, so I think `G/E, 80/362` is proper

**Comment by moonso** [comment]
Ok, next problem with this one:
`aa_change` and `aa_length` is on gene level not transcript level in gemini. 
So we will only get information for the most severe change. Not sure how/where to display this..
We can not display it on transcript level since it will not be true for all transcripts and in the gene table it would also be misguiding since it is only information about one transcript.

**Comment by moonso** [comment]
Sorry I might have been mistaken about this...
